name: Setup node
description: Setup Node and restore cache

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version-file: "./.nvmrc"
        package-manager-cache: false

    - uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2
      with:
        bun-version-file: ".bun-version"

    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('bun.lockb') }}

    - name: Install node modules
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: bun install --frozen-lockfile
