name: Setup node
description: Setup Node and restore cache

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version-file: "./.nvmrc"
        package-manager-cache: false

    - uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2
      with:
        bun-version-file: ".bun-version"

    - name: Install node modules
      shell: bash
      run: bun install --frozen-lockfile
