/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedMomentsIndexRouteImport } from './routes/_authed.moments.index'
import { Route as AuthedMomentsNewRouteImport } from './routes/_authed.moments.new'
import { Route as AuthedTodoIndexRouteImport } from './routes/_authed.todo.index'
import { Route as AuthedTodoCalendarRouteImport } from './routes/_authed.todo.calendar'
import { Route as AuthedTodoSettingsRouteImport } from './routes/_authed.todo.settings'
import { Route as AuthedMomentsMomentIdEditRouteImport } from './routes/_authed.moments.$momentId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMomentsIndexRoute = AuthedMomentsIndexRouteImport.update({
  id: '/moments/',
  path: '/moments/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMomentsNewRoute = AuthedMomentsNewRouteImport.update({
  id: '/moments/new',
  path: '/moments/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTodoIndexRoute = AuthedTodoIndexRouteImport.update({
  id: '/todo/',
  path: '/todo/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTodoCalendarRoute = AuthedTodoCalendarRouteImport.update({
  id: '/todo/calendar',
  path: '/todo/calendar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTodoSettingsRoute = AuthedTodoSettingsRouteImport.update({
  id: '/todo/settings',
  path: '/todo/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMomentsMomentIdEditRoute =
  AuthedMomentsMomentIdEditRouteImport.update({
    id: '/moments/$momentId/edit',
    path: '/moments/$momentId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/moments/new': typeof AuthedMomentsNewRoute
  '/todo/calendar': typeof AuthedTodoCalendarRoute
  '/todo/settings': typeof AuthedTodoSettingsRoute
  '/moments/': typeof AuthedMomentsIndexRoute
  '/todo/': typeof AuthedTodoIndexRoute
  '/moments/$momentId/edit': typeof AuthedMomentsMomentIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/moments/new': typeof AuthedMomentsNewRoute
  '/todo/calendar': typeof AuthedTodoCalendarRoute
  '/todo/settings': typeof AuthedTodoSettingsRoute
  '/moments': typeof AuthedMomentsIndexRoute
  '/todo': typeof AuthedTodoIndexRoute
  '/moments/$momentId/edit': typeof AuthedMomentsMomentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/moments/new': typeof AuthedMomentsNewRoute
  '/_authed/todo/calendar': typeof AuthedTodoCalendarRoute
  '/_authed/todo/settings': typeof AuthedTodoSettingsRoute
  '/_authed/moments/': typeof AuthedMomentsIndexRoute
  '/_authed/todo/': typeof AuthedTodoIndexRoute
  '/_authed/moments/$momentId/edit': typeof AuthedMomentsMomentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/moments/new'
    | '/todo/calendar'
    | '/todo/settings'
    | '/moments/'
    | '/todo/'
    | '/moments/$momentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/moments/new'
    | '/todo/calendar'
    | '/todo/settings'
    | '/moments'
    | '/todo'
    | '/moments/$momentId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/moments/new'
    | '/_authed/todo/calendar'
    | '/_authed/todo/settings'
    | '/_authed/moments/'
    | '/_authed/todo/'
    | '/_authed/moments/$momentId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/moments/': {
      id: '/_authed/moments/'
      path: '/moments'
      fullPath: '/moments/'
      preLoaderRoute: typeof AuthedMomentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/moments/new': {
      id: '/_authed/moments/new'
      path: '/moments/new'
      fullPath: '/moments/new'
      preLoaderRoute: typeof AuthedMomentsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/todo/': {
      id: '/_authed/todo/'
      path: '/todo'
      fullPath: '/todo/'
      preLoaderRoute: typeof AuthedTodoIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/todo/calendar': {
      id: '/_authed/todo/calendar'
      path: '/todo/calendar'
      fullPath: '/todo/calendar'
      preLoaderRoute: typeof AuthedTodoCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/todo/settings': {
      id: '/_authed/todo/settings'
      path: '/todo/settings'
      fullPath: '/todo/settings'
      preLoaderRoute: typeof AuthedTodoSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/moments/$momentId/edit': {
      id: '/_authed/moments/$momentId/edit'
      path: '/moments/$momentId/edit'
      fullPath: '/moments/$momentId/edit'
      preLoaderRoute: typeof AuthedMomentsMomentIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedMomentsNewRoute: typeof AuthedMomentsNewRoute
  AuthedTodoCalendarRoute: typeof AuthedTodoCalendarRoute
  AuthedTodoSettingsRoute: typeof AuthedTodoSettingsRoute
  AuthedMomentsIndexRoute: typeof AuthedMomentsIndexRoute
  AuthedTodoIndexRoute: typeof AuthedTodoIndexRoute
  AuthedMomentsMomentIdEditRoute: typeof AuthedMomentsMomentIdEditRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedMomentsNewRoute: AuthedMomentsNewRoute,
  AuthedTodoCalendarRoute: AuthedTodoCalendarRoute,
  AuthedTodoSettingsRoute: AuthedTodoSettingsRoute,
  AuthedMomentsIndexRoute: AuthedMomentsIndexRoute,
  AuthedTodoIndexRoute: AuthedTodoIndexRoute,
  AuthedMomentsMomentIdEditRoute: AuthedMomentsMomentIdEditRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
