/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedMomentsIndexRouteImport } from './routes/_authed.moments.index'
import { Route as AuthedMomentsNewRouteImport } from './routes/_authed.moments.new'
import { Route as AuthedMomentsMomentIdEditRouteImport } from './routes/_authed.moments.$momentId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMomentsIndexRoute = AuthedMomentsIndexRouteImport.update({
  id: '/moments/',
  path: '/moments/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMomentsNewRoute = AuthedMomentsNewRouteImport.update({
  id: '/moments/new',
  path: '/moments/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMomentsMomentIdEditRoute =
  AuthedMomentsMomentIdEditRouteImport.update({
    id: '/moments/$momentId/edit',
    path: '/moments/$momentId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/moments/new': typeof AuthedMomentsNewRoute
  '/moments/': typeof AuthedMomentsIndexRoute
  '/moments/$momentId/edit': typeof AuthedMomentsMomentIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/moments/new': typeof AuthedMomentsNewRoute
  '/moments': typeof AuthedMomentsIndexRoute
  '/moments/$momentId/edit': typeof AuthedMomentsMomentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/moments/new': typeof AuthedMomentsNewRoute
  '/_authed/moments/': typeof AuthedMomentsIndexRoute
  '/_authed/moments/$momentId/edit': typeof AuthedMomentsMomentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/moments/new' | '/moments/' | '/moments/$momentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/moments/new' | '/moments' | '/moments/$momentId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/moments/new'
    | '/_authed/moments/'
    | '/_authed/moments/$momentId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/moments/': {
      id: '/_authed/moments/'
      path: '/moments'
      fullPath: '/moments/'
      preLoaderRoute: typeof AuthedMomentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/moments/new': {
      id: '/_authed/moments/new'
      path: '/moments/new'
      fullPath: '/moments/new'
      preLoaderRoute: typeof AuthedMomentsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/moments/$momentId/edit': {
      id: '/_authed/moments/$momentId/edit'
      path: '/moments/$momentId/edit'
      fullPath: '/moments/$momentId/edit'
      preLoaderRoute: typeof AuthedMomentsMomentIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedMomentsNewRoute: typeof AuthedMomentsNewRoute
  AuthedMomentsIndexRoute: typeof AuthedMomentsIndexRoute
  AuthedMomentsMomentIdEditRoute: typeof AuthedMomentsMomentIdEditRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedMomentsNewRoute: AuthedMomentsNewRoute,
  AuthedMomentsIndexRoute: AuthedMomentsIndexRoute,
  AuthedMomentsMomentIdEditRoute: AuthedMomentsMomentIdEditRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
