import { randomUUID } from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as readline from 'node:readline';
import type { DsqlArticle, DynamoArticle } from './types.js';

// 固定UUID（変更しないこと）
const _FIXED_ROLE_ID = '00000000-0000-0000-0000-000000000001';
const FIXED_USER_ID = '00000000-0000-0000-0000-000000000002';

// Unix timestamp (ms) → ISO8601
function msToIso8601(ms: number): string {
  return new Date(ms).toISOString();
}

// SQLエスケープ（シングルクォートをエスケープ）
function escapeSql(str: string): string {
  return str.replace(/'/g, "''");
}

// DynamoDB → DSQL Article 変換
function convertArticle(dynamo: DynamoArticle): DsqlArticle {
  const status = dynamo.typePublishAt ? 'published' : 'draft';

  // descriptionがない場合はtitleを使用し、警告ログを出力
  let description = dynamo.description;
  if (!description) {
    console.warn(
      `[WARN] No description for article: ${dynamo.articleId} (${dynamo.title})`
    );
    description = dynamo.title;
  }

  return {
    article_id: randomUUID(),
    title: dynamo.title,
    slug: dynamo.articleId,
    user_id: FIXED_USER_ID,
    content: dynamo.content,
    thumbnail: dynamo.thumbnail ?? null,
    description,
    status,
    type: dynamo.type,
    published_at: dynamo.publishAt ? msToIso8601(dynamo.publishAt) : null,
    created_at: msToIso8601(dynamo.createAt),
    updated_at: msToIso8601(dynamo.updateAt),
  };
}

// Article INSERT文生成
function generateArticleInsert(article: DsqlArticle): string {
  const thumbnail = article.thumbnail
    ? `'${escapeSql(article.thumbnail)}'`
    : 'NULL';
  const publishedAt = article.published_at
    ? `'${article.published_at}'`
    : 'NULL';

  return `INSERT INTO app.articles (article_id, title, slug, user_id, content, thumbnail, description, status, type, published_at, created_at, updated_at) VALUES ('${article.article_id}', '${escapeSql(article.title)}', '${escapeSql(article.slug)}', '${article.user_id}', '${escapeSql(article.content)}', ${thumbnail}, '${escapeSql(article.description)}', '${article.status}', '${article.type}', ${publishedAt}, '${article.created_at}', '${article.updated_at}');`;
}

// 98_seed_data.sql 生成（固定データ: users）
function generateBaseSeedSql(outputDir: string): void {
  const outputPath = path.join(outputDir, '98_seed_data.sql');
  const lines = [
    '-- Generated by dsql-cli convert',
    '-- 固定シードデータ（users）',
    '',
    '-- Users',
    `INSERT INTO app.users (user_id, name, email) VALUES ('${FIXED_USER_ID}', 'shuntaka', 'shuntaka9576@gmail.com');`,
  ];

  fs.writeFileSync(outputPath, `${lines.join('\n')}\n`);
  console.log(`Output: ${outputPath}`);
}

// メイン変換処理
export async function convertJsonlToSql(
  inputPath: string,
  outputPath: string
): Promise<void> {
  const fileStream = fs.createReadStream(inputPath);
  const rl = readline.createInterface({
    input: fileStream,
    crlfDelay: Number.POSITIVE_INFINITY,
  });

  const articles: DsqlArticle[] = [];

  for await (const line of rl) {
    if (line.trim()) {
      const dynamo = JSON.parse(line) as DynamoArticle;
      articles.push(convertArticle(dynamo));
    }
  }

  // SQL生成
  const now = new Date().toISOString();
  const lines: string[] = [
    '-- Generated by dsql-cli convert',
    `-- Source: ${inputPath}`,
    `-- Generated at: ${now}`,
    '',
    `-- Articles (${articles.length} records)`,
    ...articles.map(generateArticleInsert),
  ];

  fs.writeFileSync(outputPath, `${lines.join('\n')}\n`);
  console.log(`Converted ${articles.length} articles`);
  console.log(`Output: ${outputPath}`);

  // 98_seed_data.sql も生成
  const outputDir = path.dirname(outputPath);
  generateBaseSeedSql(outputDir);
}
