[package]
name = "blog-api"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"
path = "src/bin/app.rs"

[dependencies]
adapter.workspace = true
api.workspace = true
infrastructure.workspace = true
registry.workspace = true
shared.workspace = true
anyhow.workspace = true
tokio.workspace = true
axum.workspace = true
sqlx.workspace = true
async-trait.workspace = true
derive-new.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-opentelemetry.workspace = true
