[config]
default_to_workspace = false

[env]
PORT = "8080"
AWS_REGION = "ap-northeast-1"

[env.development]
DSQL_CLUSTER_ENDPOINT = { script = [
  "aws ssm get-parameter --name '/dev/shuntaka/dsql/cluster-endpoint' --query 'Parameter.Value' --output text",
] }

[tasks.run]
env_files = [".env"]
command = "cargo"
args = ["watch", "-x", "run"]

[tasks.build]
command = "cargo"
args = ["build", "${@}"]

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all", "${@}"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all", "--all-targets", "${@}"]
