name: CI

on: [push]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2

      - name: Lint
        shell: bash
        run: pnpm lint

      - name: Spell check
        shell: bash
        run: pnpm spell-check

      - name: Type check
        shell: bash
        run: pnpm type-check

      - name: Test
        shell: bash
        run: pnpm run test
