name: Deploy

on:
  push:
    branches:
      - preview
      - main
  workflow_dispatch:
    inputs:
      stageName:
        description: "Deploy stage"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prd

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-${{ inputs.stageName || (github.ref_name == 'main' && 'prd' || 'dev') }}
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      stageName: ${{ inputs.stageName || (github.ref_name == 'main' && 'prd' || 'dev') }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
