name: Deploy

on:
  workflow_dispatch:
    inputs:
      stageName:
        description: "Deploy stage"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prd

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      stageName: ${{ inputs.stageName || 'dev' }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
