name: Deploy (Reusable)

on:
  workflow_call:
    inputs:
      stageName:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        required: true
      GH_APP_ID:
        required: true
      CLOUDINARY_CLOUD_NAME:
        required: true
      CLOUDINARY_API_KEY:
        required: true

jobs:
  deploy:
    runs-on: [self-hosted, macOS, ARM64]
    timeout-minutes: 30
    environment: ${{ inputs.stageName }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: ./.github/actions/setup-node

      - name: Setup Rust
        uses: ./.github/actions/setup-rust

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ inputs.stageName }}-shuntaka-assume-role
          aws-region: ap-northeast-1

      - name: CDK Deploy
        working-directory: iac/aws
        run: pnpm exec cdk deploy "${{ inputs.stageName == 'prd' && 'p' || 'd' }}-st-main" -c stageName=${{ inputs.stageName }} --require-approval never
        env:
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_APP_SECRET_PEM_KEY_NAME: ${{ vars.GH_APP_SECRET_PEM_KEY_NAME }}
          GH_WEBHOOK_SECRET_KEY_NAME: ${{ vars.GH_WEBHOOK_SECRET_KEY_NAME }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET_KEY_NAME: ${{ vars.CLOUDINARY_API_SECRET_KEY_NAME }}
