apiVersion: v1
kind: Service
metadata:
  name: tidb-public
  namespace: tidb-cluster
  annotations:
    tailscale.com/expose: 'true'
    tailscale.com/hostname: 'tidb'
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/component: tidb
    app.kubernetes.io/instance: basic
  ports:
    - port: 4000
      targetPort: 4000
